/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2026 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include "main.h"
#include "OSKernal.h"
#include"led.h"
#include"uart.h"

volatile int tick_time;


void task0(void){

	while(1)
	{
		GPIOA->ODR ^= LED;
		tick_time=0;
		while(tick_time < 1600000)
		{
			tick_time++;
		}
	}


}

void task1(void){
    while(1){
    	uart_write('g');
    	for(volatile int i=0;i<300000;i++);
    }
}

void task2(void){
    while(1){
    }
}
int main()
{
	led_init();
	uart_init();
	OsKernal_init();
	osKernelAddThreads(&task0,&task1,&task2);
	OsKernalLaunch(QUANTA);
}
